Dev: add Dockerfile
DSMFOREST/DSMBamBoo-Backend pull request #3
Opened 2020-05-12 01:33 UTC by by09115

# 구현 내용
- Dockerfile 추가

# 도입 혹은 구현하게 된 계기
- CD Pipeline 구성

# 추후 보강해야 할 부분
- 이미지 크기 최적화 필요

2020-05-12 01:58 UTC, SammyOut requested changes
pr이 너무 큽니다 아래 정도로 나눴으면 좋았을 거 같아요
1. project setup or java, gradle version up
2. 회원가입 구현
3. 게시글 작성 기능
4. dockerfile 추가

최대한 변경 라인 400라인 이하, 변경파일 10개 이하로 잡아주세요 (강요는 아니고 권고입니당)

2020-05-12 01:58 UTC, SangminOut commented on Dockerfile
> +ENTRYPOINT ["java","-jar","/app.jar"]
eof 추가해주세요

2020-05-12 01:58 UTC, SangminOut commented on Dockerfile
> +COPY ${JAR_FILE} app.jar
```suggestion
ADD ./build/libs/*.jar app.jar
```
굳이 arg로 받을 필요는 없을거 같고 요렇게 치환?

2020-05-12 01:58 UTC, SangminOut commented on Dockerfile
> +ARG JAR_FILE=build/libs/*.jar
profile env를 받을 수 있으면 좋을거 같아요~

2020-05-12 01:58 UTC, SangminOut commented on src/main/java/com/dsmbamboo/api/ApiApplication.java
> +package com.dsmbamboo.api;
nit; `com.dsm.bamboo', `com.dsm.bamboo.api' 는 어때요?

2020-05-12 01:58 UTC, SangminOut commented on src/main/java/com/dsmbamboo/api/domains/notices/model/Notice.java
> +public class Notice {
db erd 그려서 공유 해주세요

2020-05-12 01:58 UTC, SangminOut commented on src/main/java/com/dsmbamboo/api/domains/notices/model/Notice.java
> +@AllArgsConstructor
builder가 있는데 `@NoArgsConstructor`, `@AllArgsConstructor` 가 들어가는 이유가 있을까요?

2020-05-12 01:58 UTC, SangminOut commented on src/main/java/com/dsmbamboo/api/domains/posts/model/Article.java
> +    private Draft draft;
임시저장 느낌의 필드일거 같은데 one to one 보다는 flag field 추가하는건 어떨까요?

2020-05-12 01:58 UTC, SangminOut commented on src/main/java/com/dsmbamboo/api/domains/posts/model/Article.java
> +    private LocalDateTime createdAt;
updated_at 도 넣어줘요~

2020-05-12 01:58 UTC, SangminOut commented on src/main/java/com/dsmbamboo/api/domains/notices/model/Notice.java
> +    private LocalDateTime createdAt;
updated at도 넣어줘요

2020-05-12 01:58 UTC, SangminOut commented on src/main/java/com/dsmbamboo/api/domains/posts/model/Category.java
> +    private String name;
모든 db table에는 관리차 created_at, updated_at 넣어주세요~

2020-05-12 01:58 UTC, SangminOut commented on src/main/java/com/dsmbamboo/api/domains/posts/model/Draft.java
> +    private boolean isVisible;
db 컬럼에서는 is_xxx 보다는 xxx_flag를 더 많이 쓰는거 같더라구요

2020-05-12 01:58 UTC, SangminOut commented on src/main/java/com/dsmbamboo/api/domains/notices/model/NoticeRepository.java
> +public interface NoticeRepository extends CrudRepository<Notice, Long> {
CrudRepository 보다는 좀 더 커스터마이즈 해서 쓸 수 있는 JpaRepository 가 선호되는 거 같더라구요

2020-05-12 02:11 UTC, by09115 commented on Dockerfile
> +ENTRYPOINT ["java","-jar","/app.jar"]
넵

2020-05-12 02:14 UTC, by09115 commented on src/main/java/com/dsmbamboo/api/domains/notices/model/Notice.java
> +@AllArgsConstructor
이전 코드 긁어오면서 검수가 미숙했습니다. 수정하겠습니다.

2020-05-12 02:15 UTC, by09115 commented on src/main/java/com/dsmbamboo/api/domains/posts/model/Article.java
> +    private LocalDateTime createdAt;
JPA 상속 관계 구성해서 추가하도록 하겠습니다.

2020-05-12 02:16 UTC, by09115 commented on src/main/java/com/dsmbamboo/api/domains/posts/model/Draft.java
> +    private boolean isVisible;
수정하겠습니다.

2020-05-12 02:29 UTC, by09115 commented on Dockerfile
> +ARG JAR_FILE=build/libs/*.jar
`docker run -d -p 8080:8080 -e "SPRING_PROFILES_ACTIVE=dev" --name rest-api dockerImage:latest`
이런식으로 구동하면 Dockerfile에 별도로 추가하지 않아도 될 것 같은데 어떻게 생각하시나요?

2020-05-12 02:34 UTC, by09115 commented on Dockerfile
> +ENTRYPOINT ["java","-jar","/app.jar"]
#7a5d4ee 참고 부탁드립니다.

2020-05-12 02:35 UTC, by09115 commented on Dockerfile
> +COPY ${JAR_FILE} app.jar
#7a5d4ee 에 반영했습니다.

2020-05-12 02:35 UTC, SangminOut commented on Dockerfile
> +ENTRYPOINT ["java","-jar","/app.jar"]
# 떼면 이렇게 7a5d4ee 링크 뚫려요

2020-05-12 02:36 UTC, SangminOut commented on Dockerfile
> +ARG JAR_FILE=build/libs/*.jar
그럼 `SPRING_PROFILES_ACTIVE` 라는 env 가 추가되어야 하지 않을까요? 없어도 잘 돌아가낭

2020-05-12 02:37 UTC, by09115 commented on src/main/java/com/dsmbamboo/api/ApiApplication.java
> +package com.dsmbamboo.api;
서버 도메인이 `com.dsmbamboo`로 구성되어 있어 관례대로 진행했습니다.

2020-05-12 02:37 UTC, SangminOut commented on src/main/java/com/dsmbamboo/api/ApiApplication.java
> +package com.dsmbamboo.api;
org가 dsmbamboo구나 이건 패스해용

2020-05-12 02:43 UTC, by09115 commented on src/main/java/com/dsmbamboo/api/domains/posts/model/Article.java
> +    private Draft draft;
수정하겠습니다.

2020-05-12 02:48 UTC, by09115 commented on Dockerfile
> +ARG JAR_FILE=build/libs/*.jar
http://www.littlebigextra.com/use-spring-profiles-docker-containers/#Passing-Spring-Profile-in-Docker-run
직접 구동되는 것을 확인했습니다.

2020-05-12 09:49 UTC, SangminOut commented on Dockerfile
> +ARG JAR_FILE=build/libs/*.jar
오케이 굳

2020-05-12 15:17 UTC, by09115 commented on src/main/java/com/dsmbamboo/api/domains/notices/model/Notice.java
> +public class Notice {
![db](https://user-images.githubusercontent.com/36767009/81712002-250cb980-94af-11ea-9440-a9830ce53c1f.png)

2020-05-12 15:21 UTC, by09115 commented on src/main/java/com/dsmbamboo/api/domains/notices/model/Notice.java
> +public class Notice {
![db](https://user-images.githubusercontent.com/36767009/81712492-9e0c1100-94af-11ea-93e5-71013b6b22ec.png)

2020-05-13 00:35 UTC, by09115 commented on src/main/java/com/dsmbamboo/api/domains/notices/model/Notice.java
> +public class Notice {
![image](https://user-images.githubusercontent.com/36767009/81758517-07fed780-94fd-11ea-9ac1-062e9964b555.png)

2020-05-13 00:35 UTC, by09115 commented on src/main/java/com/dsmbamboo/api/domains/notices/model/Notice.java
> +public class Notice {
![db](https://user-images.githubusercontent.com/36767009/81758546-1b11a780-94fd-11ea-9020-4249a5e1fab7.png)

2020-05-21 23:40 UTC, by09115 commented
#5 PR에 피드백을 적용하여 업데이트했습니다.

2020-05-26 00:47 UTC, by09115 commented
PR 규모가 너무 커서 분할 조치하겠습니다.

2020-05-26 00:47 UTC, closed without merging

2020-05-26 00:49 UTC, by09115 commented on src/main/java/com/dsmbamboo/api/domains/notices/model/Notice.java
> +@AllArgsConstructor
@Entity 사용 시 @NoArgsConstructor가 필요한데, @Builder를 이용하는 경우 @NoArgsConstructor가 있으면 @AllArgsConstructor 또한 작성이 필요합니다. 추후 커밋에서 수정했습니다.